In [1]:
# Import dependecies
import pandas as pd
import numpy as np

In [4]:
# Import data for pre-processing
production_df = pd.read_csv('../data.csv')
df.head(10)

,id,imdb_id,popularity,budget,revenue,original_title,cast,homepage,director,tagline,...,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year,budget_adj,revenue_adj
0,135397,tt0369610,32.985763,150000000,1513528810,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,http://www.jurassicworld.com/,Colin Trevorrow,The park is open.,...,Twenty-two years after the events of Jurassic ...,124,Action|Adventure|Science Fiction|Thriller,Universal Studios|Amblin Entertainment|Legenda...,6/9/2015,5562,6.5,2015,1.379999e+08,1.392446e+09
1,76341,tt1392190,28.419936,150000000,378436354,Mad Max: Fury Road,Tom Hardy|Charlize Theron|Hugh Keays-Byrne|Nic...,http://www.madmaxmovie.com/,George Miller,What a Lovely Day.,...,An apocalyptic story set in the furthest reach...,120,Action|Adventure|Science Fiction|Thriller,Village Roadshow Pictures|Kennedy Miller Produ...,5/13/2015,6185,7.1,2015,1.379999e+08,3.481613e+08
2,262500,tt2908446,13.112507,110000000,295238201,Insurgent,Shailene Woodley|Theo James|Kate Winslet|Ansel...,http://www.thedivergentseries.movie/#insurgent,Robert Schwentke,One Choice Can Destroy You,...,Beatrice Prior must confront her inner demons ...,119,Adventure|Science Fiction|Thriller,Summit Entertainment|Mandeville Films|Red Wago...,3/18/2015,2480,6.3,2015,1.012000e+08,2.716190e+08
3,140607,tt2488496,11.173104,200000000,2068178225,Star Wars: The Force Awakens,Harrison Ford|Mark Hamill|Carrie Fisher|Adam D...,http://www.starwars.com/films/star-wars-episod...,J.J. Abrams,Every generation has a story.,...,Thirty years after defeating the Galactic Empi...,136,Action|Adventure|Science Fiction|Fantasy,Lucasfilm|Truenorth Productions|Bad Robot,12/15/2015,5292,7.5,2015,1.839999e+08,1.902723e+09
4,168259,tt2820852,9.335014,190000000,1506249360,Furious 7,Vin Diesel|Paul Walker|Jason Statham|Michelle ...,http://www.furious7.com/,James Wan,Vengeance Hits Home,...,Deckard Shaw seeks revenge against Dominic Tor...,137,Action|Crime|Thriller,Universal Pictures|Original Film|Media Rights ...,4/1/2015,2947,7.3,2015,1.747999e+08,1.385749e+09
5,281957,tt1663202,9.110700,135000000,532950503,The Revenant,Leonardo DiCaprio|Tom Hardy|Will Poulter|Domhn...,http://www.foxmovies.com/movies/the-revenant,Alejandro GonzÃ¡lez IÃ±Ã¡rritu,"(n. One who has returned, as if from the dead.)",...,"In the 1820s, a frontiersman, Hugh Glass, sets...",156,Western|Drama|Adventure|Thriller,Regency Enterprises|Appian Way|CatchPlay|Anony...,12/25/2015,3929,7.2,2015,1.241999e+08,4.903142e+08
6,87101,tt1340138,8.654359,155000000,440603537,Terminator Genisys,Arnold Schwarzenegger|Jason Clarke|Emilia Clar...,http://www.terminatormovie.com/,Alan Taylor,Reset the future,...,"The year is 2029. John Connor, leader of the r...",125,Science Fiction|Action|Thriller|Adventure,Paramount Pictures|Skydance Productions,6/23/2015,2598,5.8,2015,1.425999e+08,4.053551e+08
7,286217,tt3659388,7.667400,108000000,595380321,The Martian,Matt Damon|Jessica Chastain|Kristen Wiig|Jeff ...,http://www.foxmovies.com/movies/the-martian,Ridley Scott,Bring Him Home,...,"During a manned mission to Mars, Astronaut Mar...",141,Drama|Adventure|Science Fiction,Twentieth Century Fox Film Corporation|Scott F...,9/30/2015,4572,7.6,2015,9.935996e+07,5.477497e+08
8,211672,tt2293640,7.404165,74000000,1156730962,Minions,Sandra Bullock|Jon Hamm|Michael Keaton|Allison...,http://www.minionsmovie.com/,Kyle Balda|Pierre Coffin,"Before Gru, they had a history of bad bosses",...,"Minions Stuart, Kevin and Bob are recruited by...",91,Family|Animation|Adventure|Comedy,Universal Pictures|Illumination Entertainment,6/17/2015,2893,6.5,2015,6.807997e+07,1.064192e+09
9,150540,tt2096673,6.326804,175000000,853708609,Inside Out,Amy Poehler|Phyllis Smith|Richard Kind|Bill Ha...,http://movies.disney.com/inside-out,Pete Docter,Meet the little voices inside your head.,...,"Growing up can be a bumpy road, and it's no ex...",94,Comedy|Animation|Family,Walt Disney Pictures|Pixar Animation Studios|W...,6/9/2015,3935,8.0,2015,1.609999e+08,7.854116e+08

In [6]:
production_df['release_date'] = pd.to_datetime(production_df['release_date'])
production_df['release_date'][:10]

0   2015-06-09
1   2015-05-13
2   2015-03-18
3   2015-12-15
4   2015-04-01
5   2015-12-25
6   2015-06-23
7   2015-09-30
8   2015-06-17
9   2015-06-09
Name: release_date, dtype: datetime64[ns]

In [8]:
production_df['release_year'] = production_df['release_date'].dt.year
production_df['release_year']

0        2015
1        2015
2        2015
3        2015
4        2015
         ...
10861    1966
10862    1966
10863    1966
10864    1966
10865    1966
Name: release_year, Length: 10866, dtype: int64

In [10]:
production_df = production_df.loc[(production_df['release_year'] >= 1961) & (df['release_year'] <= 2015)]
production_df.head(10)

,id,imdb_id,popularity,budget,revenue,original_title,cast,homepage,director,tagline,...,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year,budget_adj,revenue_adj
0,135397,tt0369610,32.985763,150000000,1513528810,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,http://www.jurassicworld.com/,Colin Trevorrow,The park is open.,...,Twenty-two years after the events of Jurassic ...,124,Action|Adventure|Science Fiction|Thriller,Universal Studios|Amblin Entertainment|Legenda...,2015-06-09,5562,6.5,2015,1.379999e+08,1.392446e+09
1,76341,tt1392190,28.419936,150000000,378436354,Mad Max: Fury Road,Tom Hardy|Charlize Theron|Hugh Keays-Byrne|Nic...,http://www.madmaxmovie.com/,George Miller,What a Lovely Day.,...,An apocalyptic story set in the furthest reach...,120,Action|Adventure|Science Fiction|Thriller,Village Roadshow Pictures|Kennedy Miller Produ...,2015-05-13,6185,7.1,2015,1.379999e+08,3.481613e+08
2,262500,tt2908446,13.112507,110000000,295238201,Insurgent,Shailene Woodley|Theo James|Kate Winslet|Ansel...,http://www.thedivergentseries.movie/#insurgent,Robert Schwentke,One Choice Can Destroy You,...,Beatrice Prior must confront her inner demons ...,119,Adventure|Science Fiction|Thriller,Summit Entertainment|Mandeville Films|Red Wago...,2015-03-18,2480,6.3,2015,1.012000e+08,2.716190e+08
3,140607,tt2488496,11.173104,200000000,2068178225,Star Wars: The Force Awakens,Harrison Ford|Mark Hamill|Carrie Fisher|Adam D...,http://www.starwars.com/films/star-wars-episod...,J.J. Abrams,Every generation has a story.,...,Thirty years after defeating the Galactic Empi...,136,Action|Adventure|Science Fiction|Fantasy,Lucasfilm|Truenorth Productions|Bad Robot,2015-12-15,5292,7.5,2015,1.839999e+08,1.902723e+09
4,168259,tt2820852,9.335014,190000000,1506249360,Furious 7,Vin Diesel|Paul Walker|Jason Statham|Michelle ...,http://www.furious7.com/,James Wan,Vengeance Hits Home,...,Deckard Shaw seeks revenge against Dominic Tor...,137,Action|Crime|Thriller,Universal Pictures|Original Film|Media Rights ...,2015-04-01,2947,7.3,2015,1.747999e+08,1.385749e+09
5,281957,tt1663202,9.110700,135000000,532950503,The Revenant,Leonardo DiCaprio|Tom Hardy|Will Poulter|Domhn...,http://www.foxmovies.com/movies/the-revenant,Alejandro GonzÃ¡lez IÃ±Ã¡rritu,"(n. One who has returned, as if from the dead.)",...,"In the 1820s, a frontiersman, Hugh Glass, sets...",156,Western|Drama|Adventure|Thriller,Regency Enterprises|Appian Way|CatchPlay|Anony...,2015-12-25,3929,7.2,2015,1.241999e+08,4.903142e+08
6,87101,tt1340138,8.654359,155000000,440603537,Terminator Genisys,Arnold Schwarzenegger|Jason Clarke|Emilia Clar...,http://www.terminatormovie.com/,Alan Taylor,Reset the future,...,"The year is 2029. John Connor, leader of the r...",125,Science Fiction|Action|Thriller|Adventure,Paramount Pictures|Skydance Productions,2015-06-23,2598,5.8,2015,1.425999e+08,4.053551e+08
7,286217,tt3659388,7.667400,108000000,595380321,The Martian,Matt Damon|Jessica Chastain|Kristen Wiig|Jeff ...,http://www.foxmovies.com/movies/the-martian,Ridley Scott,Bring Him Home,...,"During a manned mission to Mars, Astronaut Mar...",141,Drama|Adventure|Science Fiction,Twentieth Century Fox Film Corporation|Scott F...,2015-09-30,4572,7.6,2015,9.935996e+07,5.477497e+08
8,211672,tt2293640,7.404165,74000000,1156730962,Minions,Sandra Bullock|Jon Hamm|Michael Keaton|Allison...,http://www.minionsmovie.com/,Kyle Balda|Pierre Coffin,"Before Gru, they had a history of bad bosses",...,"Minions Stuart, Kevin and Bob are recruited by...",91,Family|Animation|Adventure|Comedy,Universal Pictures|Illumination Entertainment,2015-06-17,2893,6.5,2015,6.807997e+07,1.064192e+09
9,150540,tt2096673,6.326804,175000000,853708609,Inside Out,Amy Poehler|Phyllis Smith|Richard Kind|Bill Ha...,http://movies.disney.com/inside-out,Pete Docter,Meet the little voices inside your head.,...,"Growing up can be a bumpy road, and it's no ex...",94,Comedy|Animation|Family,Walt Disney Pictures|Pixar Animation Studios|W...,2015-06-09,3935,8.0,2015,1.609999e+08,7.854116e+08

In [11]:
production_df.shape

(10834, 21)

In [17]:
production_df = production_df.drop_duplicates(subset=['original_title'], keep='first')
production_df.head(10)

,id,imdb_id,popularity,budget,revenue,original_title,cast,homepage,director,tagline,...,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year,budget_adj,revenue_adj
0,135397,tt0369610,32.985763,150000000,1513528810,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,http://www.jurassicworld.com/,Colin Trevorrow,The park is open.,...,Twenty-two years after the events of Jurassic ...,124,Action|Adventure|Science Fiction|Thriller,Universal Studios|Amblin Entertainment|Legenda...,2015-06-09,5562,6.5,2015,1.379999e+08,1.392446e+09
1,76341,tt1392190,28.419936,150000000,378436354,Mad Max: Fury Road,Tom Hardy|Charlize Theron|Hugh Keays-Byrne|Nic...,http://www.madmaxmovie.com/,George Miller,What a Lovely Day.,...,An apocalyptic story set in the furthest reach...,120,Action|Adventure|Science Fiction|Thriller,Village Roadshow Pictures|Kennedy Miller Produ...,2015-05-13,6185,7.1,2015,1.379999e+08,3.481613e+08
2,262500,tt2908446,13.112507,110000000,295238201,Insurgent,Shailene Woodley|Theo James|Kate Winslet|Ansel...,http://www.thedivergentseries.movie/#insurgent,Robert Schwentke,One Choice Can Destroy You,...,Beatrice Prior must confront her inner demons ...,119,Adventure|Science Fiction|Thriller,Summit Entertainment|Mandeville Films|Red Wago...,2015-03-18,2480,6.3,2015,1.012000e+08,2.716190e+08
3,140607,tt2488496,11.173104,200000000,2068178225,Star Wars: The Force Awakens,Harrison Ford|Mark Hamill|Carrie Fisher|Adam D...,http://www.starwars.com/films/star-wars-episod...,J.J. Abrams,Every generation has a story.,...,Thirty years after defeating the Galactic Empi...,136,Action|Adventure|Science Fiction|Fantasy,Lucasfilm|Truenorth Productions|Bad Robot,2015-12-15,5292,7.5,2015,1.839999e+08,1.902723e+09
4,168259,tt2820852,9.335014,190000000,1506249360,Furious 7,Vin Diesel|Paul Walker|Jason Statham|Michelle ...,http://www.furious7.com/,James Wan,Vengeance Hits Home,...,Deckard Shaw seeks revenge against Dominic Tor...,137,Action|Crime|Thriller,Universal Pictures|Original Film|Media Rights ...,2015-04-01,2947,7.3,2015,1.747999e+08,1.385749e+09
5,281957,tt1663202,9.110700,135000000,532950503,The Revenant,Leonardo DiCaprio|Tom Hardy|Will Poulter|Domhn...,http://www.foxmovies.com/movies/the-revenant,Alejandro GonzÃ¡lez IÃ±Ã¡rritu,"(n. One who has returned, as if from the dead.)",...,"In the 1820s, a frontiersman, Hugh Glass, sets...",156,Western|Drama|Adventure|Thriller,Regency Enterprises|Appian Way|CatchPlay|Anony...,2015-12-25,3929,7.2,2015,1.241999e+08,4.903142e+08
6,87101,tt1340138,8.654359,155000000,440603537,Terminator Genisys,Arnold Schwarzenegger|Jason Clarke|Emilia Clar...,http://www.terminatormovie.com/,Alan Taylor,Reset the future,...,"The year is 2029. John Connor, leader of the r...",125,Science Fiction|Action|Thriller|Adventure,Paramount Pictures|Skydance Productions,2015-06-23,2598,5.8,2015,1.425999e+08,4.053551e+08
7,286217,tt3659388,7.667400,108000000,595380321,The Martian,Matt Damon|Jessica Chastain|Kristen Wiig|Jeff ...,http://www.foxmovies.com/movies/the-martian,Ridley Scott,Bring Him Home,...,"During a manned mission to Mars, Astronaut Mar...",141,Drama|Adventure|Science Fiction,Twentieth Century Fox Film Corporation|Scott F...,2015-09-30,4572,7.6,2015,9.935996e+07,5.477497e+08
8,211672,tt2293640,7.404165,74000000,1156730962,Minions,Sandra Bullock|Jon Hamm|Michael Keaton|Allison...,http://www.minionsmovie.com/,Kyle Balda|Pierre Coffin,"Before Gru, they had a history of bad bosses",...,"Minions Stuart, Kevin and Bob are recruited by...",91,Family|Animation|Adventure|Comedy,Universal Pictures|Illumination Entertainment,2015-06-17,2893,6.5,2015,6.807997e+07,1.064192e+09
9,150540,tt2096673,6.326804,175000000,853708609,Inside Out,Amy Poehler|Phyllis Smith|Richard Kind|Bill Ha...,http://movies.disney.com/inside-out,Pete Docter,Meet the little voices inside your head.,...,"Growing up can be a bumpy road, and it's no ex...",94,Comedy|Animation|Family,Walt Disney Pictures|Pixar Animation Studios|W...,2015-06-09,3935,8.0,2015,1.609999e+08,7.854116e+08

In [19]:
production_df['film'] = production_df['original_title']
production_df['film']

0                      Jurassic World
1                  Mad Max: Fury Road
2                           Insurgent
3        Star Wars: The Force Awakens
4                           Furious 7
                     ...
10861              The Endless Summer
10862                      Grand Prix
10863             Beregis Avtomobilya
10864          What's Up, Tiger Lily?
10865        Manos: The Hands of Fate
Name: film, Length: 10546, dtype: object

In [21]:
production_df = production_df.drop(['original_title'], axis = 1)

In [23]:
production_df.shape

(10546, 21)

In [5]:
oscars_df = pd.read_csv('the_oscar_award.csv')
oscars_df.head(10)

,year_film,year_ceremony,ceremony,category,name,film,winner
0,1927,1928,1,ACTOR,Richard Barthelmess,The Noose,False
1,1927,1928,1,ACTOR,Emil Jannings,The Last Command,True
2,1927,1928,1,ACTRESS,Louise Dresser,A Ship Comes In,False
3,1927,1928,1,ACTRESS,Janet Gaynor,7th Heaven,True
4,1927,1928,1,ACTRESS,Gloria Swanson,Sadie Thompson,False
5,1927,1928,1,ART DIRECTION,Rochus Gliese,Sunrise,False
6,1927,1928,1,ART DIRECTION,William Cameron Menzies,The Dove;,True
7,1927,1928,1,ART DIRECTION,Harry Oliver,7th Heaven,False
8,1927,1928,1,CINEMATOGRAPHY,George Barnes,The Devil Dancer;,False
9,1927,1928,1,CINEMATOGRAPHY,Charles Rosher,Sunrise,True

In [13]:
oscars_df = oscars_df.loc[(oscars_df['year_film'] >= 1961) & (oscars_df['year_film'] < 2016)]
oscars_df.head(10)

,year_film,year_ceremony,ceremony,category,name,film,winner
3714,1961,1962,34,ACTOR,Charles Boyer,Fanny,False
3715,1961,1962,34,ACTOR,Paul Newman,The Hustler,False
3716,1961,1962,34,ACTOR,Maximilian Schell,Judgment at Nuremberg,True
3717,1961,1962,34,ACTOR,Spencer Tracy,Judgment at Nuremberg,False
3718,1961,1962,34,ACTOR,Stuart Whitman,The Mark,False
3719,1961,1962,34,ACTOR IN A SUPPORTING ROLE,George Chakiris,West Side Story,True
3720,1961,1962,34,ACTOR IN A SUPPORTING ROLE,Montgomery Clift,Judgment at Nuremberg,False
3721,1961,1962,34,ACTOR IN A SUPPORTING ROLE,Peter Falk,Pocketful of Miracles,False
3722,1961,1962,34,ACTOR IN A SUPPORTING ROLE,Jackie Gleason,The Hustler,False
3723,1961,1962,34,ACTOR IN A SUPPORTING ROLE,George C. Scott,The Hustler,False

In [14]:
oscars_df.shape

(6175, 7)

In [15]:
oscars_df = oscars_df.drop_duplicates(subset=['film'], keep='first')
oscars_df.head(10)

,year_film,year_ceremony,ceremony,category,name,film,winner
3714,1961,1962,34,ACTOR,Charles Boyer,Fanny,False
3715,1961,1962,34,ACTOR,Paul Newman,The Hustler,False
3716,1961,1962,34,ACTOR,Maximilian Schell,Judgment at Nuremberg,True
3718,1961,1962,34,ACTOR,Stuart Whitman,The Mark,False
3719,1961,1962,34,ACTOR IN A SUPPORTING ROLE,George Chakiris,West Side Story,True
3721,1961,1962,34,ACTOR IN A SUPPORTING ROLE,Peter Falk,Pocketful of Miracles,False
3724,1961,1962,34,ACTRESS,Audrey Hepburn,Breakfast at Tiffany's,False
3726,1961,1962,34,ACTRESS,Sophia Loren,Two Women,True
3727,1961,1962,34,ACTRESS,Geraldine Page,Summer and Smoke,False
3728,1961,1962,34,ACTRESS,Natalie Wood,Splendor in the Grass,False

In [16]:
oscars_df.shape

(2871, 7)

In [24]:
merged_df = production_df.merge(oscars_df, on='film', how='outer')
merged_df.head(10)

,id,imdb_id,popularity,budget,revenue,cast,homepage,director,tagline,keywords,...,release_year,budget_adj,revenue_adj,film,year_film,year_ceremony,ceremony,category,name,winner
0,135397.0,tt0369610,32.985763,150000000.0,1.513529e+09,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,http://www.jurassicworld.com/,Colin Trevorrow,The park is open.,monster|dna|tyrannosaurus rex|velociraptor|island,...,2015.0,1.379999e+08,1.392446e+09,Jurassic World,NaN,NaN,NaN,NaN,NaN,NaN
1,76341.0,tt1392190,28.419936,150000000.0,3.784364e+08,Tom Hardy|Charlize Theron|Hugh Keays-Byrne|Nic...,http://www.madmaxmovie.com/,George Miller,What a Lovely Day.,future|chase|post-apocalyptic|dystopia|australia,...,2015.0,1.379999e+08,3.481613e+08,Mad Max: Fury Road,2015.0,2016.0,88.0,CINEMATOGRAPHY,John Seale,False
2,262500.0,tt2908446,13.112507,110000000.0,2.952382e+08,Shailene Woodley|Theo James|Kate Winslet|Ansel...,http://www.thedivergentseries.movie/#insurgent,Robert Schwentke,One Choice Can Destroy You,based on novel|revolution|dystopia|sequel|dyst...,...,2015.0,1.012000e+08,2.716190e+08,Insurgent,NaN,NaN,NaN,NaN,NaN,NaN
3,140607.0,tt2488496,11.173104,200000000.0,2.068178e+09,Harrison Ford|Mark Hamill|Carrie Fisher|Adam D...,http://www.starwars.com/films/star-wars-episod...,J.J. Abrams,Every generation has a story.,android|spaceship|jedi|space opera|3d,...,2015.0,1.839999e+08,1.902723e+09,Star Wars: The Force Awakens,2015.0,2016.0,88.0,FILM EDITING,Maryann Brandon and Mary Jo Markey,False
4,168259.0,tt2820852,9.335014,190000000.0,1.506249e+09,Vin Diesel|Paul Walker|Jason Statham|Michelle ...,http://www.furious7.com/,James Wan,Vengeance Hits Home,car race|speed|revenge|suspense|car,...,2015.0,1.747999e+08,1.385749e+09,Furious 7,NaN,NaN,NaN,NaN,NaN,NaN
5,281957.0,tt1663202,9.110700,135000000.0,5.329505e+08,Leonardo DiCaprio|Tom Hardy|Will Poulter|Domhn...,http://www.foxmovies.com/movies/the-revenant,Alejandro GonzÃ¡lez IÃ±Ã¡rritu,"(n. One who has returned, as if from the dead.)",father-son relationship|rape|based on novel|mo...,...,2015.0,1.241999e+08,4.903142e+08,The Revenant,2015.0,2016.0,88.0,ACTOR IN A LEADING ROLE,Leonardo DiCaprio,True
6,87101.0,tt1340138,8.654359,155000000.0,4.406035e+08,Arnold Schwarzenegger|Jason Clarke|Emilia Clar...,http://www.terminatormovie.com/,Alan Taylor,Reset the future,saving the world|artificial intelligence|cybor...,...,2015.0,1.425999e+08,4.053551e+08,Terminator Genisys,NaN,NaN,NaN,NaN,NaN,NaN
7,286217.0,tt3659388,7.667400,108000000.0,5.953803e+08,Matt Damon|Jessica Chastain|Kristen Wiig|Jeff ...,http://www.foxmovies.com/movies/the-martian,Ridley Scott,Bring Him Home,based on novel|mars|nasa|isolation|botanist,...,2015.0,9.935996e+07,5.477497e+08,The Martian,2015.0,2016.0,88.0,ACTOR IN A LEADING ROLE,Matt Damon,False
8,211672.0,tt2293640,7.404165,74000000.0,1.156731e+09,Sandra Bullock|Jon Hamm|Michael Keaton|Allison...,http://www.minionsmovie.com/,Kyle Balda|Pierre Coffin,"Before Gru, they had a history of bad bosses",assistant|aftercreditsstinger|duringcreditssti...,...,2015.0,6.807997e+07,1.064192e+09,Minions,NaN,NaN,NaN,NaN,NaN,NaN
9,150540.0,tt2096673,6.326804,175000000.0,8.537086e+08,Amy Poehler|Phyllis Smith|Richard Kind|Bill Ha...,http://movies.disney.com/inside-out,Pete Docter,Meet the little voices inside your head.,dream|cartoon|imaginary friend|animation|kid,...,2015.0,1.609999e+08,7.854116e+08,Inside Out,2015.0,2016.0,88.0,ANIMATED FEATURE FILM,Pete Docter and Jonas Rivera,True

In [25]:
merged_df.shape

(12116, 27)

In [27]:
merged_df.head(10)

,id,imdb_id,popularity,budget,revenue,cast,homepage,director,tagline,keywords,...,release_year,budget_adj,revenue_adj,film,year_film,year_ceremony,ceremony,category,name,winner
0,135397.0,tt0369610,32.985763,150000000.0,1.513529e+09,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,http://www.jurassicworld.com/,Colin Trevorrow,The park is open.,monster|dna|tyrannosaurus rex|velociraptor|island,...,2015.0,1.379999e+08,1.392446e+09,Jurassic World,NaN,NaN,NaN,NaN,NaN,NaN
1,76341.0,tt1392190,28.419936,150000000.0,3.784364e+08,Tom Hardy|Charlize Theron|Hugh Keays-Byrne|Nic...,http://www.madmaxmovie.com/,George Miller,What a Lovely Day.,future|chase|post-apocalyptic|dystopia|australia,...,2015.0,1.379999e+08,3.481613e+08,Mad Max: Fury Road,2015.0,2016.0,88.0,CINEMATOGRAPHY,John Seale,False
2,262500.0,tt2908446,13.112507,110000000.0,2.952382e+08,Shailene Woodley|Theo James|Kate Winslet|Ansel...,http://www.thedivergentseries.movie/#insurgent,Robert Schwentke,One Choice Can Destroy You,based on novel|revolution|dystopia|sequel|dyst...,...,2015.0,1.012000e+08,2.716190e+08,Insurgent,NaN,NaN,NaN,NaN,NaN,NaN
3,140607.0,tt2488496,11.173104,200000000.0,2.068178e+09,Harrison Ford|Mark Hamill|Carrie Fisher|Adam D...,http://www.starwars.com/films/star-wars-episod...,J.J. Abrams,Every generation has a story.,android|spaceship|jedi|space opera|3d,...,2015.0,1.839999e+08,1.902723e+09,Star Wars: The Force Awakens,2015.0,2016.0,88.0,FILM EDITING,Maryann Brandon and Mary Jo Markey,False
4,168259.0,tt2820852,9.335014,190000000.0,1.506249e+09,Vin Diesel|Paul Walker|Jason Statham|Michelle ...,http://www.furious7.com/,James Wan,Vengeance Hits Home,car race|speed|revenge|suspense|car,...,2015.0,1.747999e+08,1.385749e+09,Furious 7,NaN,NaN,NaN,NaN,NaN,NaN
5,281957.0,tt1663202,9.110700,135000000.0,5.329505e+08,Leonardo DiCaprio|Tom Hardy|Will Poulter|Domhn...,http://www.foxmovies.com/movies/the-revenant,Alejandro GonzÃ¡lez IÃ±Ã¡rritu,"(n. One who has returned, as if from the dead.)",father-son relationship|rape|based on novel|mo...,...,2015.0,1.241999e+08,4.903142e+08,The Revenant,2015.0,2016.0,88.0,ACTOR IN A LEADING ROLE,Leonardo DiCaprio,True
6,87101.0,tt1340138,8.654359,155000000.0,4.406035e+08,Arnold Schwarzenegger|Jason Clarke|Emilia Clar...,http://www.terminatormovie.com/,Alan Taylor,Reset the future,saving the world|artificial intelligence|cybor...,...,2015.0,1.425999e+08,4.053551e+08,Terminator Genisys,NaN,NaN,NaN,NaN,NaN,NaN
7,286217.0,tt3659388,7.667400,108000000.0,5.953803e+08,Matt Damon|Jessica Chastain|Kristen Wiig|Jeff ...,http://www.foxmovies.com/movies/the-martian,Ridley Scott,Bring Him Home,based on novel|mars|nasa|isolation|botanist,...,2015.0,9.935996e+07,5.477497e+08,The Martian,2015.0,2016.0,88.0,ACTOR IN A LEADING ROLE,Matt Damon,False
8,211672.0,tt2293640,7.404165,74000000.0,1.156731e+09,Sandra Bullock|Jon Hamm|Michael Keaton|Allison...,http://www.minionsmovie.com/,Kyle Balda|Pierre Coffin,"Before Gru, they had a history of bad bosses",assistant|aftercreditsstinger|duringcreditssti...,...,2015.0,6.807997e+07,1.064192e+09,Minions,NaN,NaN,NaN,NaN,NaN,NaN
9,150540.0,tt2096673,6.326804,175000000.0,8.537086e+08,Amy Poehler|Phyllis Smith|Richard Kind|Bill Ha...,http://movies.disney.com/inside-out,Pete Docter,Meet the little voices inside your head.,dream|cartoon|imaginary friend|animation|kid,...,2015.0,1.609999e+08,7.854116e+08,Inside Out,2015.0,2016.0,88.0,ANIMATED FEATURE FILM,Pete Docter and Jonas Rivera,True

In [26]:
merged_df.tail(30)

,id,imdb_id,popularity,budget,revenue,cast,homepage,director,tagline,keywords,...,release_year,budget_adj,revenue_adj,film,year_film,year_ceremony,ceremony,category,name,winner
12086,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,The Dam Keeper,2014.0,2015.0,87.0,SHORT FILM (Animated),Robert Kondo and Dice Tsutsumi,False
12087,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Me and My Moulton,2014.0,2015.0,87.0,SHORT FILM (Animated),Torill Kove,False
12088,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,A Single Life,2014.0,2015.0,87.0,SHORT FILM (Animated),Joris Oprins,False
12089,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Aya,2014.0,2015.0,87.0,SHORT FILM (Live Action),Oded Binnun and Mihal Brezis,False
12090,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Boogaloo and Graham,2014.0,2015.0,87.0,SHORT FILM (Live Action),Michael Lennox and Ronan Blaney,False
12091,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Butter Lamp (La Lampe Au Beurre De Yak),2014.0,2015.0,87.0,SHORT FILM (Live Action),Hu Wei and Julien Féret,False
12092,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Parvaneh,2014.0,2015.0,87.0,SHORT FILM (Live Action),Talkhon Hamzavi and Stefan Eichenberger,False
12093,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,The Phone Call,2014.0,2015.0,87.0,SHORT FILM (Live Action),Mat Kirkby and James Lucas,True
12094,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Boy and the World,2015.0,2016.0,88.0,ANIMATED FEATURE FILM,Alê Abreu,False
12095,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,When Marnie Was There,2015.0,2016.0,88.0,ANIMATED FEATURE FILM,Hiromasa Yonebayashi and Yoshiaki Nishimura,False
12096,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Body Team 12,2015.0,2016.0,88.0,DOCUMENTARY (Short Subject),David Darg and Bryn Mooser,False
12097,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,"Chau, beyond the Lines",2015.0,2016.0,88.0,DOCUMENTARY (Short Subject),Courtney Marsh and Jerry Franck,False
12098,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Claude Lanzmann: Spectres of the Shoah,2015.0,2016.0,88.0,DOCUMENTARY (Short Subject),Adam Benzine,False
12099,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,A Girl in the River: The Price of Forgiveness,2015.0,2016.0,88.0,DOCUMENTARY (Short Subject),Sharmeen Obaid-Chinoy,True
12100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Last Day of Freedom,2015.0,2016.0,88.0,DOCUMENTARY (Short Subject),Dee Hibbert-Jones and Nomi Talisman,False
12101,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Embrace of the Serpent,2015.0,2016.0,88.0,FOREIGN LANGUAGE FILM,Colombia,False
12102,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Mustang,2015.0,2016.0,88.0,FOREIGN LANGUAGE FILM,France,False
12103,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Son of Saul,2015.0,2016.0,88.0,FOREIGN LANGUAGE FILM,Hungary,True
12104,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Theeb,2015.0,2016.0,88.0,FOREIGN LANGUAGE FILM,Jordan,False
12105,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,A War,2015.0,2016.0,88.0,FOREIGN LANGUAGE FILM,Denmark,False
12106,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,The 100-Year-Old Man Who Climbed out the Windo...,2015.0,2016.0,88.0,MAKEUP AND HAIRSTYLING,Love Larson and Eva von Bahr,False
12107,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Youth,2015.0,2016.0,88.0,MUSIC (Original Song),Music and Lyric by David Lang,False
12108,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Bear Story,2015.0,2016.0,88.0,SHORT FILM (Animated),Gabriel Osorio and Pato Escala,True
12109,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Prologue,2015.0,2016.0,88.0,SHORT FILM (Animated),Richard Williams and Imogen Sutton,False
12110,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,We Can't Live without Cosmos,2015.0,2016.0,88.0,SHORT FILM (Animated),Konstantin Bronzit,False
12111,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Ave Maria,2015.0,2016.0,88.0,SHORT FILM (Live Action),Basil Khalil and Eric Dupont,False
12112,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Day One,2015.0,2016.0,88.0,SHORT FILM (Live Action),Henry Hughes,False
12113,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Everything Will Be Okay (Alles Wird Gut),2015.0,2016.0,88.0,SHORT FILM (Live Action),Patrick Vollrath,False
12114,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Shok,2015.0,2016.0,88.0,SHORT FILM (Live Action),Jamie Donoughue,False
12115,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Stutterer,2015.0,2016.0,88.0,SHORT FILM (Live Action),Benjamin Cleary and Serena Armitage,True

In [30]:
duplicates = merged_df.duplicated(subset='film')
num_duplicates = duplicates.sum()
print(f"There are {num_duplicates} duplicates in the merged dataframe.")

There are 0 duplicates in the merged dataframe.

In [31]:
merged_df.to_csv('merged_dataframe.csv', index=False)